class_name Anim
extends RefCounted

## Animation names in player_frames.tres (generated by
## tools/generate_player_frames.py). Referencing these avoids typos and makes
## renames greppable.

const IDLE := "idle"
const WALK := "walk"          # speed-tier: low ground speed (visual only)
const RUN := "run"
const SPRINT := "sprint"      # speed-tier: near top speed (visual only)
const JUMP := "jump"
const JUMP_APEX := "jump_apex"  # 3-stage jump: rise -> apex -> fall
const FALL := "fall"
const LAND := "land"          # brief landing hold (drives squash + dust)
const RUN_STOP := "run_stop"  # run/sprint decelerating into idle
const IDLE_IN := "idle_in"    # transition into idle
const SLIDE := "slide"
const CRAWL := "crawl"
const CROUCH := "crouch"
const ROLL := "roll"          # tunnel exit-stun tumble (Runner)
const ATTACK := "attack"
const GRAB := "grab"          # Hunter's one-shot lunge / pounce reach (not the mash-off)
const STRUGGLE := "struggle"  # Runner thrashing to break the grip during the mash-off
const PUSH := "push"          # Hunter shoving during the mash-off
const PULL := "pull"          # unused: struggle uses ShockHeavy instead of this heave
const FAINT := "faint"        # Hunter dazed after a Runner escapes its grip
const DIE := "die"            # Hunter killed
