class_name Anim
extends RefCounted

## Animation names in player_frames.tres (generated by
## tools/generate_player_frames.py). Referencing these avoids typos and makes
## renames greppable.

const IDLE := "idle"
const RUN := "run"
const JUMP := "jump"
const FALL := "fall"
const SLIDE := "slide"
const CRAWL := "crawl"
const CROUCH := "crouch"
const ATTACK := "attack"
const GRAB := "grab"          # Hunter suppression hold
const STRUGGLE := "struggle"  # Runner being suppressed
const DIE := "die"            # Hunter killed
